openapi: 3.0.1
info:
  title: Ads System
  version: 1.0.0
servers:
  - url: https://makediff.herokuapp.com
tags:
  - name: user
    description: Operations about user
  - name: shop
    description: Operations about shop
  - name: post
    description: Operations about post
paths:
  /api/user/new:
    post:
      tags:
        - user
      summary: Create user
      description: Create user
      operationId: CreateUser
      requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /api/user/pre-login:
    post:
      tags:
        - user
      summary: Get token before login
      description: Get token before login
      operationId: PreAuthenticate
      requestBody:
        description: Pre-login data object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /api/user/login:
    post:
      tags:
        - user
      summary: Login user account
      description: Login user account
      operationId: Authenticate
      requestBody:
        description: User object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /api/user/social-login:
    post:
      tags:
        - user
      summary: Login with social account
      description: This can only be done by the logged in user.
      operationId: SocialAuthenticate
      requestBody:
        description: Pre-login data object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body


  /api/shop-category/list:
    get:
      tags:
        - shop
      summary: Get list category of shops
      description: This can only be done by the logged in user.
      operationId: ShopCategoryList
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShopListType'
      x-codegen-request-body-name: body


  /api/shop-list/type-list:
    get:
      tags:
        - shop
      summary: Get list type of shop
      description: This can only be done by the logged in user.
      operationId: ShopListTypes
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShopListType'
      x-codegen-request-body-name: body

  /api/shop-list/new:
    get:
      tags:
        - shop
      summary: Get list shop type new
      description: This can only be done by the logged in user.
      operationId: ShopListNew
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShopListItem'
      x-codegen-request-body-name: body

  /api/shop-list/hot:
    get:
      tags:
        - shop
      summary: Get list shop type hot
      description: This can only be done by the logged in user.
      operationId: ShopListHot
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShopListItem'
      x-codegen-request-body-name: body

  /api/shop/details:
    get:
      tags:
        - shop
      summary: Get list shop type hot
      description: This can only be done by the logged in user.
      parameters:
        - in: query
          name: shop_id
          schema:
            type: integer
          description: Id of shop
      operationId: ShopDetail
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShopDetail'
      x-codegen-request-body-name: body

  /api/shop/products:
    get:
      tags:
        - shop
      summary: Get list shop type hot
      description: This can only be done by the logged in user.
      operationId: ShopProducts
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /api/shop/subscribe:
    get:
      tags:
        - shop
      summary: Get list shop type hot
      description: This can only be done by the logged in user.
      operationId: Subscribe
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /api/shop/new:
    post:
      tags:
        - shop
      summary: Get list shop type hot
      description: This can only be done by the logged in user.
      operationId: Create shop
      requestBody:
        description: Pre-login data object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /api/post-category/list:
    get:
      tags:
        - post
      summary: Get list category of posts
      description: This can only be done by the logged in user.
      operationId: PostCategoryList
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostCategory'
      x-codegen-request-body-name: body


components:
  schemas:

    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        user_id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        category:
          type: integer
          format: int64
        discount:
          type: integer
          format: int64
        discount_percent:
          type: integer
          format: int64
        class:
          type: integer
          format: int64
        hide:
          type: integer
          format: int64
        view_number:
          type: integer
          format: int64
        start_date:
          type: integer
          format: int64
        end_date:
          type: integer
          format: int64
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64

    PostCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        icon_url:
          type: string

    Shop:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        user_id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
        location_id:
          type: integer
          format: int64
        cover_url:
          type: string
        banner_url:
          type: string
        icon_url:
          type: string
        phone_number:
          type: string
        description:
          type: string
        short_description:
          type: string
        shop_category:
          type: integer
          format: int64
        shared_num:
          type: integer
          format: int64
        visited_num:
          type: integer
          format: int64
        created_time:
          type: integer
          format: int64
        updated_time:
          type: integer
          format: int64

    ShopProduct:
      type: object
      properties:
        id:
          type: integer
          format: int64
        shop_id:
          type: integer
          format: int64
        product_id:
          type: integer
          format: int64
        inventory:
          type: integer
          format: int64
        sale_percent:
          type: integer
          format: int64
        sale_from_date:
          type: integer
          format: int64
        sale_to_date:
          type: integer
          format: int64

    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
        image_url:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        category_id:
          type: integer
          format: int64
        created_time:
          type: integer
          format: int64
        updated_time:
          type: integer
          format: int64

    ShopCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        icon_url:
          type: string

    ShopListType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        icon_url:
          type: string

    ShopListItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        shop_name:
          type: string
        image_url:
          type: string
        short_description:
          type: string
        create_time:
          type: integer
          format: int64
        update_time:
          type: integer
          format: int64

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password_hash:
          type: string
        salt:
          type: string
        gender:
          type: integer
          format: int64
        age:
          type: integer
          format: int64
        address:
          type: string
        email:
          type: string
        phone:
          type: string
        avatar_url:
          type: string
        banner_url:
          type: string
        fb_uid:
          type: string
        gg_uid:
          type: string
        created_time:
          type: integer
          format: int64
        updated_time:
          type: integer
          format: int64

    Address:
      type: object
      properties:
        name:
          type: string
        custom_name:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float

    ShopDetail:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        avatar_url:
          type: string
        banner_url:
          type: string
        cover_url:
          type: string
        description:
          type: string
        follower_num:
          type: integer
          format: int64
        following_num:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        last_online:
          type: integer
          format: int64
        name:
          type: string


    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
