package org.example.app.units

import com.makediff.library.SharedFactory
import dev.icerock.moko.units.TableUnitItem

//class PostCateUnitsFactory : SharedFactory.PostCategoryUnitsFactory {
//    override fun createCateTile(
//        id: Long,
//        title: String,
//        iconUrl: String
//    ): TableUnitItem {
//        // TileNews is generated by units plugin from https://github.com/icerockdev/moko-units
//        // generation based on databinding layouts
//        return TilePostCate().apply {
//        }
//    }
//}